### ISSUE TITLE
Missing '=' in .get_sent_sms_list()

### ISSUE THREAD

**Issue by ghost** [xoxzo/xoxzo.cloudpy#17]
In cloudpy.py line 143, should there be a '=' after the query string?

Line 143: url = self.xoxzo_api_sms_url + '?sent_date' + sent_date

**Comment by anonaka** [comment]
List api will take not only "=" operator but also takes comparison operators such as "<","<=", etc. Thus we cannot hardcode "=" here.

https://docs.xoxzo.com/en/sms.html#sent-messages-list-api

**Comment by ghost** [comment]
Ah! the operator should be included in the sent_date variable itself. Got it. Thanks!

**Comment by anonaka** [comment]
I appreciate your comments anyway.
